version: '3'

services:
  nextjs:
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - "3000"
    
  nginx:
    image: nginx:latest
    ports:
      - "35443:35443"  # Пробрасываем порт 35443 с контейнера на хост
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certificates:/etc/nginx/certificates:ro
    depends_on:
      - nextjs
